### ISSUE TITLE
Unknown rates type in macOS

### ISSUE THREAD

**Issue by eric940109** [qojulia/QuantumCumulants.jl#106]
Dear contributors of QuantumCumulants,

First, thanks for the super useful package!

I recently encountered an issue that when 'rates' contains operations, e.g. '+' and '*', the code can't run in macOS but works well in Windows. The error message is "Unknown rates type!". 

I wonder is there any solution to this?

My macOS is Catalina 10.15.7 installed in MacBook Pro (13 inches, 2015 early).

Here is the code (reproduced from Zhang et al., arXiv:2203.04102v1, 2022).

using QuantumCumulants
kbT = 1.380649e-23*293; # J/K*K =J, room temperature
kb = 1.380649e-23; # J/K
hh = 6.62607015e-34; #  Planck's constant,unit J.s
hbar = 6.62607015e-34/(2*pi);
@cnumbers N Δ31 ξ ksp k47 k57 k67 k73 k72 k71 k31 k13 k21 k12 χ2 χ3
@cnumbers Δm g31 κ nmth  ωd
hm = FockSpace(:resonator)
hNV_ = NLevelSpace(:NV,7)
hNV = ClusterSpace(hNV_,N,2)
h = hm ⊗ hNV
@qnumbers a::Destroy(h)
σ(i,j) = Transition(h,:σ,i,j,2)
H = Δ31*sum(σ(3,3)) + Δm*a'a + g31*(a'*sum(σ(1,3)) + a*sum(σ(3,1))) ;
J = [σ(4,1),σ(5,2),σ(6,3),σ(1,4),σ(2,5),σ(3,6),σ(7,4),σ(7,5),
    σ(7,6),σ(2,7),σ(3,7),σ(1,7),σ(1,2),σ(1,3),σ(2,1),σ(3,1),σ(2,2),σ(3,3),a,a']
rates = [ξ,ξ,ξ,ξ+ksp,ξ+ksp,ξ+ksp,k47,k57,k67,k73,k72,k71,k21,k31,k12,k13,2*χ2,2*χ3,(1.0+nmth)*κ,nmth*κ];
ops = [a'*a,σ(2,2)[1],σ(3,3)[1]]
eqs = meanfield(ops,H,J;rates=rates,order=2)
eqs_c = complete(eqs,order=2);

and error message.

<img width="961" alt="Unknow rates type" src="https://user-images.githubusercontent.com/44778525/169188165-5ba94f83-04b4-46ac-b21c-71a01ebb3a2e.png">

Thank you!

Best wishes,
Eric

**Comment by ChristophHotter** [comment]
Hi @eric940109 ,

Thank you! 
Did you check if you have the latest version of QuantumCumulants.jl?
For rates including +, * or also time dependent rates you need version v0.2.6 or higher.

**Comment by eric940109** [comment]
> Hi @eric940109 ,
> 
> Thank you! Did you check if you have the latest version of QuantumCumulants.jl? For rates including +, * or also time dependent rates you need version v0.2.6 or higher.

Hi @ChristophHotter ,

Thanks for your swift help! Updating the QuantumCumulants package solves the problem.

Best wishes,
Eric
