### ISSUE TITLE
to_numeric yields wrong results for larger Hilbert space

### ISSUE THREAD

**Issue by davidschlegel** [qojulia/QuantumCumulants.jl#109]
When taking a larger Fock cutoff, to_numeric yields wrong results in some cases.
Example:
``` 
using QuantumCumulants
using QuantumOptics

hfock = FockSpace(:fock)
@qnumbers a::Destroy(hfock)
bfock = FockBasis(100)

diff = (2*create(bfock)+2*destroy(bfock)) - to_numeric((2*(a)+2*(a')), bfock)
```
The difference `diff` between these operators is non-zero.

The conversion from symbolic to numeric operators in `QuantumOptics` causes solvers to fail since I think it breaks Hermiticity.
Any idea what causes this strange behavior?

**Comment by david-pl** [comment]
Thanks for the bug report @davidschlegel. There is an issue with the conversion of multiplication expressions. I created a PR with the fix.

**Comment by ChristophHotter** [comment]
@davidschlegel it should work now with version 0.2.8

**Comment by davidschlegel** [comment]
Thanks for the fix!
