### ISSUE TITLE
`test_correlation.jl` fails for newer `Symbolics.jl` versions

### ISSUE THREAD

**Issue by jkosata** [qojulia/QuantumCumulants.jl#115]
I am trying to use `QuantumCumulants.jl` functionality in `HarmonicBalance.jl`, https://github.com/NonlinearOscillations/HarmonicBalance.jl . The latter relies on newer version of `Symbolics.jl`, but the former is capped at < 4.3.1

Updating to 4.11.0 gives

![2022-10-12_14-09](https://user-images.githubusercontent.com/58295890/195339010-a2eb55e1-8993-4830-951f-760ddffa1340.png)

**Comment by ChristophHotter** [comment]
Hi @jkosata,
Due to the error you mention for Symbolics version 4.11.0 we restricted the version to 4.3.1.
We still don't know what exactly causes the error, but I will try to fix it as soon as possible.

**Comment by david-pl** [comment]
@jkosata @ChristophHotter I think I've found the issue. It should be fixed in #119.

@jkosata HarmonicBalance.jl looks like a nice package! I'm really curious as to what you're trying to do. Could you share some more details?

**Comment by jkosata** [comment]
Perfect, thanks!
What we have in mind is to use the method of harmonic balance with quantum-mechanical equations of motion. Essentially expanding each QM variable in terms of one or more Fourier components and solving the resulting algebraic equations to get them. The simplest instance of this is using the rotating-wave approximation to obtain the response of a cavity.

On our end, this would be similar to the example on the title page, but with a QuantumCumulants Hamiltonian as input, instead of a Newtonian differential equation.
