### ISSUE TITLE
Simplify expressions

### ISSUE THREAD

**Issue by albertomercurio** [qojulia/QuantumCumulants.jl#127]
Hello,

I want to find a `simplify` method for this simple test code

```julia
using QuantumCumulants

# Define hilbert space
hf = FockSpace(:cavity)
ha = NLevelSpace(:atom,(:g,:e))
h = hf ⊗ ha

# Define the fundamental operators
@qnumbers a::Destroy(h) σ::Transition(h,:g,:e)

σm = σ
σp = σ'
sz = σp * σm - σm * σp

sz
```

which returns `(-1+σee+σee)` instead of `(-1+2*σee)`.
Is there a way to simplify it?

**Comment by ChristophHotter** [comment]
Hi @albertomercurio,
Yes you can use `QuantumCumulants.simplify(sz)`. I will export this function at the next release that you can use `simplify(sz)`.

**Comment by albertomercurio** [comment]
I'm using the stable version, but it says that `QuantumCumulants.simplify` doen't exist. Is it present only in the dev release?

**Comment by ChristophHotter** [comment]
Sorry my mistake.
`using Symbolics` and then `simplify(sz)` should work.

If you do `average(sz)`, it would also simplify the expression (but with expectation values in the expression).

**Comment by albertomercurio** [comment]
Perfect, it works perfectly! Thanks.
