### ISSUE TITLE
`complete` and `scale` fail when using linear combinations of operators

### ISSUE THREAD

**Issue by piperfw** [qojulia/QuantumCumulants.jl#142]
Below is the Short Example from [Symbolic Sums and Indices](https://qojulia.github.io/QuantumCumulants.jl/stable/symbolic_sums/).

```julia
using QuantumCumulants

ha = NLevelSpace(:atoms,2)
hc = FockSpace(:cavity)
h = hc ⊗ ha

@cnumbers N Δ κ γ ν

i = Index(h,:i,N,ha)
j = Index(h,:j,N,ha)

@qnumbers b::Destroy(h)
σ(x,y,z) = IndexedOperator(Transition(h,:σ,x,y),z)
gi = IndexedVariable(:g,i)

H = Δ*b'*b + ∑(gi*(b*σ(2,1,i) + b'*σ(1,2,i)),i)
ops = [b'b, σ(2,2,j)]
J = [b, σ(1,2,i), σ(2,1,i)]
rates = [κ, γ, ν]

eqs = meanfield(ops,H,J;rates=rates,order=2)
eqs_complete=complete(eqs)
```

This produces a repeated set of equations of motion, as expected. However, if I replace `b'*b` in `ops` with `2*b'*b` or (it appears) any linear combination of operators, the call to `complete` returns an error
```julia
ERROR: LoadError: MethodError: no method matching _inconj(::SymbolicUtils.Mul{CNumber, Int64, Dict{Any, Number}, Nothing})
Closest candidates are:
  _inconj(::SymbolicUtils.Term{<:QuantumCumulants.AvgSym}) at ~/.julia/packages/QuantumCumulants/MXRNL/src/index_utils.jl:59
Stacktrace:
  [1] iterate
    @ ./generator.jl:47 [inlined]
  [2] _collect(c::Vector{SymbolicUtils.Symbolic}, itr::Base.Generator{Vector{SymbolicUtils.Symbolic}, typeof(QuantumCumulants._inconj)}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:807
  [3] collect_similar(cont::Vector{SymbolicUtils.Symbolic}, itr::Base.Generator{Vector{SymbolicUtils.Symbolic}, typeof(QuantumCumulants._inconj)})
    @ Base ./array.jl:716
  [4] map(f::Function, A::Vector{SymbolicUtils.Symbolic})
    @ Base ./abstractarray.jl:2933
  [5] indexed_complete!(de::QuantumCumulants.IndexedMeanfieldEquations; order::Int64, multithread::Bool, filter_func::Nothing, mix_choice::Function, simplify::Bool, extra_indices::Vector{Symbol}, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ QuantumCumulants ~/.julia/packages/QuantumCumulants/MXRNL/src/index_meanfield.jl:321
  [6] indexed_complete!(de::QuantumCumulants.IndexedMeanfieldEquations)
    @ QuantumCumulants ~/.julia/packages/QuantumCumulants/MXRNL/src/index_meanfield.jl:203
  [7] #indexed_complete#405
    @ ~/.julia/packages/QuantumCumulants/MXRNL/src/index_meanfield.jl:194 [inlined]
  [8] indexed_complete
    @ ~/.julia/packages/QuantumCumulants/MXRNL/src/index_meanfield.jl:192 [inlined]
  [9] #complete#450
    @ ~/.julia/packages/QuantumCumulants/MXRNL/src/index_meanfield.jl:644 [inlined]
 [10] complete(eqs::QuantumCumulants.IndexedMeanfieldEquations)
    @ QuantumCumulants ~/.julia/packages/QuantumCumulants/MXRNL/src/index_meanfield.jl:644
 [11] top-level scope
```
I similarly find `scale(eqs)` does not work, this time with `MethodError: no method matching hilbert(::Int64)`. Is this expected behaviour? I am new to using Julia and the package so apologies if I am missing something obvious. My use case is taht I would like to directly determine equations of motion for operators such as sigma^z=\sigma(2,2)-\sigma(1,1) and so on, if possible.

**Comment by piperfw** [comment]
Hi @ChristophHotter, thanks for responding so quickly. That makes complete sense, just from the tutorial in the docs (which are fantastic, by the way) I didn't know whether the implementation allowed you to prescribe combinations of operators as the 'fundamental' operators in terms of which the equations should be derived. 

This (1.) might be useful because in problems with symmetries certain linear combinations of operators may greatly simplify the equations i.e. the number of variables/equations required. For example, for two distinguishable spins i and j it may be sufficient to consider im*<sigma(2,1,i)*sigma(1,2,j) -sigma(2,1,j)*sigma(1,2,i)> rather than these two products of operator separately. 
But I guess this should not be high priority since, as you say, you can construct the numerical or analytical solution for the linear combination if you need it (I was actually looking to check a set of equations I had derived by hand, hence wanted to avoid anything [2.] that could allow me to introduce my own errors!).


Thanks for linking the implementation page, I will go through this before using the package further.

**Comment by darroo** [comment]
Hi @ChristophHotter, it looks as if linear combinations of operators are similarly banned from the list of jump operators - for example the script posted by @piperfw above fails for me if I alter it to include

J = [b, σ(1,2,i), σ(2,1,i), σ(2,2,i) - σ(1,1,i)]
rates = [κ, γ, ν, χ]

to represent a pure dephasing process. Is there any way around this?

**Comment by ChristophHotter** [comment]
Hi @darroo 
There was a bug, @j-moser fixed it. It should work now in v0.2.11.

By the way, for a 2-level atom a dephasing with `σ(2,2,i) - σ(1,1,i)` is equal to `2*σ(2,2,i)`, so you could also use `σ(2,2,i)` with a sqrt(2) times larger rate.

**Comment by darroo** [comment]
Hi @ChristophHotter,

Thanks for your reply! Unfortunately I am trying to implement a 7LS to model an ensemble of diamond NV centres as in the appendix of [arXiv:2212.01864](https://arxiv.org/abs/2212.01864) so I cannot substitute 2*σ(2,2,i) for σ(2,2,i) - σ(1,1,i).

However, the complete function now runs for me in v0.2.11 with a linear combination dephasing term in the list of jump operators so all is well! Thanks for your help 🙂
