### ISSUE TITLE
Adjoint of CNumber not defined

### ISSUE THREAD

**Issue by tnadolny** [qojulia/QuantumCumulants.jl#145]
I would like to avoid the following error:
```julia
# 1st Example

h = FockSpace(:osc)
@cnumbers c
adjoint(c)

# MethodError: no method matching adjoint(::SymbolicUtils.Sym{Parameter, Base.ImmutableDict{DataType, Any}})
```

This can also happen via 
```julia
# 2nd Example

@qnumbers a::Destroy(h) 
q = (c*a+a')^2  # = (c^2*(a*a)+c*(a′*a)+(a′*a′)+c*(a′*a)+c)
adjoint(q)

# MethodError: no method matching adjoint(::SymbolicUtils.Sym{Parameter, Base.ImmutableDict{DataType, Any}})
```
or by calling `meanfield` with one of the loss terms containing `q`.

Is it a solution to add `Base.adjoint(c::SymbolicUtils.Sym) = conj(c)`?

However, if the error in the first example is desired, maybe one can avoid the error in the second example by changing 
`Base.adjoint(q::QAdd) = QAdd(map(adjoint, q.arguments))` to
`Base.adjoint(q::QAdd) = QAdd([q_arg isa QNumber ? adjoint(q_arg) : conj(q_arg) for q_arg in q.arguments])`

**Comment by ChristophHotter** [comment]
Hi @tnadolny 
I included the dispatch `Base.adjoint(c::SymbolicUtils.Sym) = conj(c)` in version 0.2.11.

**Comment by tnadolny** [comment]
Hi, 
thank you. This indeed fixes the two errors above. I realize now, I still get errors for
```julia

@cnumbers c d

adjoint(2*c)
# no method matching adjoint(::SymbolicUtils.Mul{CNumber, Int64, Dict{Any, Number}, Nothing})
adjoint(c/d)
# no method matching adjoint(::SymbolicUtils.Div{Parameter, SymbolicUtils.Sym{Parameter, Base.ImmutableDict{DataType, Any}}, SymbolicUtils.Sym{Parameter, Base.ImmutableDict{DataType, Any}}, Nothing})
adjoint(1+c)
# no method matching adjoint(::SymbolicUtils.Add{CNumber, Int64, Dict{Any, Number}, Nothing})
adjoint(c^2)
# no method matching adjoint(::SymbolicUtils.Pow{CNumber, SymbolicUtils.Sym{Parameter, Base.ImmutableDict{DataType, Any}}, Int64, Nothing})
adjoint(exp(c))
# no method matching adjoint(::SymbolicUtils.Term{CNumber, Nothing})
```

Maybe one should also define adjoint for SymbolicUtils.Mul, Div, Add, Pow and Term?

**Comment by david-pl** [comment]
@tnadolny I've relaxed the method definition to include all of the above. #147 includes the fix. @ChristophHotter if you agree with the fix, please merge and make a new release.

**Comment by tnadolny** [comment]
Thanks!
