### ISSUE TITLE
How to choose the right algorithm to compute the differential equation

### ISSUE THREAD

**Issue by MinDu183** [qojulia/QuantumCumulants.jl#175]
How to understand rigid and non-rigid problems and  Why the code can't run when i use rigid algorithms to solve differential equations.

**Comment by ChristophHotter** [comment]
Hi @MinDu183 
That's not our expertise, you should maybe check the docu [DifferentialEquations.jl](https://docs.sciml.ai/DiffEqDocs/stable/).
