### ISSUE TITLE
Periodic boundary conditions

### ISSUE THREAD

**Issue by HumpyBlumpy** [qojulia/QuantumCumulants.jl#194]
Hello,

I was reading the Symbolic-Sums-and-Indices section of the docs, but I could not find there whether I can define a model on a lattice with periodic boundary conditions.
For example, for a simple tight-binding model, I wanted to to do something like that
`ham = ∑(a(j)*a(j+1)',j)+∑(a(j)'*a(j+1),j) `
This does not work. Is there another way of achieving this?

**Comment by ChristophHotter** [comment]
Sorry for the late reply. 
Currently, it is not possible to write a Hamiltonian with shifted indices. 
You can define a Hamiltonian with a double-sum as e.g. in the [cavity antiresonance example](https://qojulia.github.io/QuantumCumulants.jl/stable/examples/cavity_antiresonance_indexed/). This includes all coupling terms, you can then just set the unnecessary ones to zero.
