### ISSUE TITLE
Problem with simplify

### ISSUE THREAD

**Issue by StefanoGregorio** [qojulia/QuantumCumulants.jl#221]
Hi, 
if I use this code

```
using QuantumCumulants
using SymbolicUtils
ha = NLevelSpace(:atom,2)
σ(α,β,i) = IndexedOperator(Transition(ha, :σ, α, β),i)
@cnumbers N 
i = Index(ha,:i,N,1)
j = Index(ha,:j,N,1)
simplify(Σ(-σ(2,2,i),i,j))
```
I get the wrong result

$`\underset{i}{\overset{N}{\sum}} -1  {\sigma}_{i}^{{22}} + \underset{i}{\overset{N}{\sum}} (-1 + N)  {\sigma}_{i}^{{22}}`$

**Comment by StefanoGregorio** [comment]
Thanks! I think the second term should have a minus so as to get the result
$` \underset{i}{\overset{N}{\sum}} (-N)  {\sigma}_{i}^{{22}}`$
It looks like there is some problem when a minus is inside the sum.

**Comment by StefanoGregorio** [comment]
Another example is when I try instead 
`simplify(Σ(2*σ(2,2,i),i,j))`
which gives 
$`\underset{i}{\overset{N}{\sum}} 2  {\sigma}_{i}^{{22}} + \underset{i}{\overset{N}{\sum}} (-1 + N)  {\sigma}_{i}^{{22}}`$
as a result, So maybe the problem is not just with the minus, but with any number multiplied by an operator inside a double sum.

**Comment by ChristophHotter** [comment]
@StefanoGregorio 
Thank you for reporting this! I found and solved the bug. I will merge it tomorrow.

**Comment by StefanoGregorio** [comment]
Great! Thank you very much!
