### ISSUE TITLE
Problem with double sums

### ISSUE THREAD

**Issue by StefanoGregorio** [qojulia/QuantumCumulants.jl#224]
Hi. Thank you again for solving the issue discussed in #221 , but I realized that in the code 

```
using QuantumCumulants
using SymbolicUtils
ha = NLevelSpace(:atom,2)
σ(α,β,i) = IndexedOperator(Transition(ha, :σ, α, β),i)
@cnumbers N 
i = Index(ha,:i,N,1)
j = Index(ha,:j,N,1)
k = Index(ha,:k,N,1)
H = Σ((-1)*σ(2,2,j),j,i)
simplify(commutator(σ(2,1,k),H))
```
there is a similar issue, probably with the function commutator. In fact, I get the wrong answer
$$\left( 1 + N \right) {\sigma}_{k}^{{21}}$$

**Comment by ChristophHotter** [comment]
@StefanoGregorio thanks again for reporting this bug. I fixed it in the new version 0.3.7.
