### ISSUE TITLE
Decay rate matrices are broken

### ISSUE THREAD

**Issue by david-pl** [qojulia/QuantumCumulants.jl#69]
There are currently two issues concerning correlated decay.

- Decay matrices get turned into vectors (where only a single row is considered) because of the call to `_expand_clusters` here: https://github.com/qojulia/QuantumCumulants.jl/blob/3cd511ea9bbb0c7f6616924853aeccb5e125bdce/src/meanfield.jl#L43
- The `rates` field in `MeanFieldEquations` is mistyped (should be `AbstractVecOrMat`) here: https://github.com/qojulia/QuantumCumulants.jl/blob/53cab7bcd5b3ff337b1071469691d2ac33290fa6/src/equations.jl#L35

@ChristophHotter  can you look into this? We also need tests.

**Comment by ChristophHotter** [comment]
Fixed in v0.1.11
Tests are also included.
