### ISSUE TITLE
Adjoint jump operators get ignored

### ISSUE THREAD

**Issue by david-pl** [qojulia/QuantumCumulants.jl#70]
We're being inconsistent with the jump operators. While we allow explicitly specifying `Jdagger` in `meanfield`, this doesn't get stored in the `MeanFieldEquations` type. This means that if there is a case where `Jdagger != adjoint.(J)`, you'd get different results depending on whether you specify a list of operators and `Jdagger` in `meanfield` or if you use `complete`. The latter will just infer `Jdagger=adjoint.(J)`.

We should either store `Jdagger` and use it where appropriate, or disallow setting `Jdagger` altogether.

**Comment by ChristophHotter** [comment]
Fixed in v0.1.11
`Jdagger` is still allowed, now it gets stored in `MeanFieldEquations`
